### ISSUE TITLE
h5 打开直接报错

### ISSUE THREAD

**Issue by nearxu** [fengyinchao/TaroCnode#1]
报错信息很奇怪，压根没用 videoUtils 这个文件。

**Comment by fengyinchao** [comment]
H5似乎還有坑，还没完全适配好

**Comment by nearxu** [comment]
昨天用了一下taro，感觉坑不止一点点，网上看了全是用redux ，我觉得简单应用没必要吧，然后发现他的this，老是指向不明undefined,不知道你平时setState有没有出现这样的问题。再次感谢你的回复。
